import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.blueGray100,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: colorScheme.onErrorContainer.withOpacity(1),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
    bodyLarge: TextStyle(
      color: colorScheme.onErrorContainer.withOpacity(1),
      fontSize: 16.fSize,
      fontFamily: 'Inter',
      fontWeight: FontWeight.w300,
    ),
    bodyMedium: TextStyle(
      color: colorScheme.onErrorContainer.withOpacity(1),
      fontSize: 14.fSize,
      fontFamily: 'Oxygen',
      fontWeight: FontWeight.w400,
    ),
    headlineLarge: TextStyle(
      color: appTheme.whiteA700,
      fontSize: 32.fSize,
      fontFamily: 'Oxygen',
      fontWeight: FontWeight.w400,
    ),
    headlineMedium: TextStyle(
      color: appTheme.gray900,
      fontSize: 26.fSize,
      fontFamily: 'Oxygen',
      fontWeight: FontWeight.w700,
    ),
    headlineSmall: TextStyle(
      color: colorScheme.onErrorContainer.withOpacity(1),
      fontSize: 25.fSize,
      fontFamily: 'Oxygen',
      fontWeight: FontWeight.w700,
    ),
    titleLarge: TextStyle(
      color: colorScheme.onErrorContainer.withOpacity(1),
      fontSize: 20.fSize,
      fontFamily: 'Inter',
      fontWeight: FontWeight.w500,
    ),
    titleMedium: TextStyle(
      color: Color(0XFF000000),
      fontSize: 16.fSize,
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
    ),
    titleSmall: TextStyle(
      color: appTheme.gray500,
      fontSize: 14.fSize,
      fontFamily: 'Oxygen',
      fontWeight: FontWeight.w700,
    ),
  );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF0274BA),
    primaryContainer: Color(0X6D1E1E1E),
    secondaryContainer: Color(0XFF6C6C6C),

    // Error colors
    errorContainer: Color(0XFF242A31),
    onErrorContainer: Color(0X3F000000),

    // On colors(text colors)
    onPrimary: Color(0XFF000C14),
    onPrimaryContainer: Color(0XFFB7B7B7),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000B14);

  // BlueGray
  Color get blueGray100 => Color(0XFFCDD1E0);
  Color get blueGray400 => Color(0XFF8390A1);

  // Gray
  Color get gray400 => Color(0XFFC5C5C5);
  Color get gray500 => Color(0XFF999EA1);
  Color get gray50001 => Color(0XFF9E9E9E);
  Color get gray900 => Color(0XFF1E232C);

  // Red
  Color get red500 => Color(0XFFEB4335);

  // Teal
  Color get teal400 => Color(0XFF18C079);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
